# Configuration default values.
# - These values can be overwritten with a custom `config.yml` in the repository base directory.
# - In the path settings, `./` denotes the repository base directory and is replaced upon loading.
paths:
  additional_data: []
  ignore_data_folders: []
  data: ./data
  supplementary_data: ./data/supplementary_data
  database: ./data/database.sqlite
  results: ./results
optimization:
  solver_name: gurobi # Must be valid solver name for CVXPY.
  show_solver_output: true # If True, activate verbose solver output.
tests:
  scenario_name: create_level8_4zones_a # Defines scenario which is considered in tests.
  show_plots: true # If True, tests may produce plots.
logs:
  level: info # Choices: `debug`, `info`, `warn`, `error`.
  format: "%(asctime)s | %(levelname)s | %(message)s"
plots:
  matplotlib_style: seaborn-v0_8-colorblind
  plotly_font_family: Arial
  plotly_font_size: 15
  plotly_figure_width: 1000
  plotly_figure_height: 500
  file_format: png
