name: cobmo
channels:
  - defaults
dependencies:
  - certifi=2019.6.16=py36_0
  - pip=19.1.1=py36_0
  - python=3.6.8=h9f7ef89_7
  - setuptools=41.0.1=py36_0
  - sqlite=3.29.0=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_4
  - wheel=0.33.4=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - appdirs==1.4.3
    - chardet==3.0.4
    - coolprop==6.2.1
    - idna==2.8
    - nose==1.3.7
    - numpy==1.16.4
    - pandas==0.24.2
    - ply==3.11
    - pvlib==0.6.3
    - pyomo==5.6.6
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pyutilib==5.7.1
    - requests==2.22.0
    - scipy==1.3.0
    - six==1.12.0
    - urllib3==1.25.3

